# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c0e7edb7162dc694276d9a08e479240f253722a06cbc2f6babc24dc23096363e4ef0e022bea8db74ab73f6f2291f4930265991acc79801cb1cb9f1c635a8ad1

test:
  secret_key_base: ecb905cb9454c4c92382e912d748aabec7f47b290e71ca7b93292503da5cc4150dc4a53ab98bedb03ec9231a54d90a3207d548d011e3f1409d331c5b02cff452

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
